config/routes.rb
Rails.application.routes.draw do
  resources :images
  root "posts#index"
  get "posts/new_tag" => "posts#new_tag"
  get "posts/create_tag" => "posts#create_tag"
  resources :posts
  
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:image_url, :story)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
  end

  def create
    Post.create(
      image_url: params[:image_url],
      story: params[:story]
    )
    redirect_to root_path
  end

  def show
    @id = params[:id]
    @post = Post.find(@id)
  end

  def edit
    @id = params[:id]
    @post = Post.find(@id)
  end

  def update
    @id = params[:id]
    @post = Post.find(@id)
    @post.update(
      image_url: params[:image_url],
      story: params[:story]
      )
    redirect_to post_path(@post.id)
  end

  def destroy
    @id = params[:id]
    Post.destroy(@id)
    redirect_to root_path
  end
  
  def new_tag
  end
  
  def create_tag
    @tag1 = params[:tag][:name1]
    @tag2 = params[:tag][:name2]
    @tag3 = params[:tag][:name3]
    @tag4 = params[:tag][:name4]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :story %><br>
    <%= f.text_field :story %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Image url</th>
      <th>Story</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.image_url %></td>
        <td><%= image.story %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image url:</strong>
  <%= @image.image_url %>
</p>

<p>
  <strong>Story:</strong>
  <%= @image.story %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/create_tag.erb
<%= @tag1%>
<%= @tag2%>
<%= @tag3%>
<%= @tag4%>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>포스트 수정하기</h1>
<%= form_tag(post_path(@post.id), method: "put") do %> <!--form_tag가 피카츄면 form_for는 라이츄-->
    이미지 주소 : <%= text_field_tag(:image_url, @post.image_url) %><br>
    글 : <%= text_field_tag(:story, @post.story) %><br>
    <%= submit_tag "수정하기" %>
<%end%>

app/views/posts/index.html.erb
<h1>Real Insta</h1>
<% @posts.each do |post|%>
    사진 : <img height = "100" width = "100" src = "<%= post.image_url%>"><%= link_to "[보기]", "/posts/#{post.id}"%><br>
<% end%>
<%= link_to "새 포스트", new_post_path %>

app/views/posts/new.html.erb
<h1>새 포스트 만들기</h1>
<%= form_tag(posts_path, method: "post") do %> <!--form_tag가 피카츄면 form_for는 라이츄-->
    이미지 주소 : <%= text_field_tag :image_url %><br>
    글 : <%= text_field_tag :story %><br>
    <%= submit_tag "만들기" %>
<%end%>

app/views/posts/new_tag.erb
<form action = "/posts/create_tag">
    <input type = "text" name = "tag[name1]">
    <input type = "text" name = "tag[name2]">
    <input type = "text" name = "tag[name3]">
    <input type = "text" name = "tag[name4]">
    <input type = "submit" value = "태그저장">
</form>

app/views/posts/show.html.erb
<h1>게시글 보기</h1>
<p>이미지 : <img height = "100" width = "100" src = "<%= @post.image_url%>"></p>
<p>글 : <%= @post.story%></p>
<%= link_to "[수정]", edit_post_path(@post.id)%>
<%= link_to "[삭제]", post_path(@post.id), method: "delete"%>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>